language: python

script:
  - python setup.py sdist

deploy:
  provider: pypi
  user: gmarull
  password:
    secure: Ecu7sOy8uGZcNrFBRpUb1I1XRO2KAYnCG6yBmIAhx6L9vpdJZhRz4uZq97sYt8UX0Q5LlHFgcmUElCalXJ+nUU9eQmCAR5aivSSAOtMNEHMzdOMFKhfcsfILRqPHD2iWShbWbnj3wCFBZx634z53wqbTdjv/ReWTZ0gCW3zopJrelXSTOQNm0vvtOLujymBMZu94m1cW2nA2se3e3QfoOlyRVOTQ78G58l6OJ91mnrAMude2U6COnCt8IGN3f52CbhVLucUVZoYwmsOBD8q9fh3JtfA7LhGLtO3/A3ViXlG4hmXBeEpNdNEErNA9Iyy5kDIbPSP7vMW8MlkCWpf4I+tVvInPTmm2h9DvmSGrLoYUnNu+kmfLQMQ9j6n3Lv9UsSD1ECJQMeDUnqwRmjKzkQe065Z0zq6hI65gHR13Y/XJFZDYF6anpjadh1tx5cixQ5dQ8ImtpaO2Au6H8B+4bLjCBKM/aCz3DEkza2R2tkjlWwLnq/B2Ua8p/DHgZffO2QiFlmq3Yjob3s1gPnC2xSjERf5CUlTjh0HjIALeDi47ICypR5xLiQk7nvMceuiduAmxfV/cwuRvZed1NHie5p0CvTeXuQ9as0JhQ3qPP0Z+T0uGlPD3uwIYCifR4aCTrAc3SrxGPq6YlhsMUoTW9yrUaMIPAgnpj0F6uZj8Q/8=
  on:
    branch: master
    tags: true
